#############################################################################
# Makefile for building: GhoseRider
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  GhoseRider.pro
# Template: app
# Command: E:\QtQt5.6.3\5.6.3\mingw49_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile GhoseRider.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = E:\QtQt5.6.3\5.6.3\mingw49_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: GhoseRider.pro E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/win32-g++/qmake.conf E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/spec_pre.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/qdevice.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/device_config.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/common/angle.conf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/qconfig.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dcore.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dinput.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dlogic.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquick.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3drender.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3drender_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axbase.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axbase_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axcontainer.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axserver.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axserver_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_bluetooth.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_clucene_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_concurrent.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_core.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_core_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_dbus.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_designer.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_designer_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_gui.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_gui_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_help.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_help_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_labscontrols_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_labstemplates_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_location.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_location_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimedia.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_network.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_network_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_nfc.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_nfc_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_opengl.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_opengl_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_openglextensions.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_positioning.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_positioning_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_printsupport.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qml.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qml_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qmltest.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quick.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quick_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_script.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_script_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_scripttools.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sensors.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sensors_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialbus.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialport.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sql.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sql_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_svg.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_svg_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_testlib.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_uiplugin.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_uitools.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_webchannel.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_websockets.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_websockets_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_widgets.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_winextras.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xml.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xml_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qt_functions.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qt_config.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/qt_config.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/win32-g++/qmake.conf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/spec_post.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/exclusive_builds.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/default_pre.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/default_pre.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/resolve_config.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/exclusive_builds_post.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/default_post.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qml_debug.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/rtti.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/precompile_header.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/warn_on.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qt.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/resources.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/moc.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/opengl.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/uic.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/file_copies.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/windows.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/testcase_targets.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/exceptions.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/yacc.prf \
		E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/lex.prf \
		GhoseRider.pro \
		E:/QtQt5.6.3/5.6.3/mingw49_32/lib/qtmaind.prl \
		E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Multimedia.prl \
		E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Widgets.prl \
		E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Gui.prl \
		E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Network.prl \
		E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile GhoseRider.pro
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/spec_pre.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/qdevice.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/device_config.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/common/angle.conf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/qconfig.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dcore.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dcore_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dinput.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dinput_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dlogic.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquick.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquick_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickinput.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickrender.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3drender.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_3drender_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axbase.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axbase_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axcontainer.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axserver.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_axserver_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_bluetooth.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_clucene_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_concurrent.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_core.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_core_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_dbus.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_dbus_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_designer.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_designer_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_gui.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_gui_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_help.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_help_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_labscontrols_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_labstemplates_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_location.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_location_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimedia.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimedia_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_network.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_network_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_nfc.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_nfc_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_opengl.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_opengl_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_openglextensions.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_positioning.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_positioning_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_printsupport.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qml.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qml_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qmltest.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qmltest_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quick.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quick_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quickwidgets.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_script.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_script_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_scripttools.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_scripttools_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sensors.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sensors_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialbus.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialbus_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialport.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_serialport_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sql.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_sql_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_svg.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_svg_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_testlib.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_testlib_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_uiplugin.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_uitools.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_uitools_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_webchannel.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_webchannel_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_websockets.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_websockets_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_widgets.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_widgets_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_winextras.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_winextras_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xml.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xml_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qt_functions.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qt_config.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/qt_config.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/win32-g++/qmake.conf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/spec_post.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/exclusive_builds.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/default_pre.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/default_pre.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/resolve_config.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/exclusive_builds_post.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/default_post.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qml_debug.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/rtti.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/precompile_header.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/warn_on.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/qt.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/resources.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/moc.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/opengl.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/uic.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/file_copies.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/win32/windows.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/testcase_targets.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/exceptions.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/yacc.prf:
E:/QtQt5.6.3/5.6.3/mingw49_32/mkspecs/features/lex.prf:
GhoseRider.pro:
E:/QtQt5.6.3/5.6.3/mingw49_32/lib/qtmaind.prl:
E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Multimedia.prl:
E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Widgets.prl:
E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Gui.prl:
E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Network.prl:
E:/QtQt5.6.3/5.6.3/mingw49_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile GhoseRider.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
